version: '3.7'

services:

  radicale:
#    image: tomsquest/docker-radicale
    build:
      context: .
      dockerfile: Dockerfile.extended
    container_name: radicale
#    ports:
#      - 127.0.0.1:55232:5232
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    environment:
      - RADICALE_NUM_USERS=2
      - RADICALE_USER1=event
      - RADICALE_PASS1=event
      - RADICALE_USER2=event_view
      - RADICALE_PASS2=event_view
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/config:ro
